// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)

// Injectors from wire.go:

func newHttpContext(contextID uint32) types.HttpContext {
	mainHttpHeaders := newHttpHeaders(contextID)
	return mainHttpHeaders
}
