apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          nodeSelector:
            ingress-ready: "true"
          volumes:
            - configMap:
                defaultMode: 420
                name: charlescd-wasm
              name: wasm
          volumeMounts:
            - mountPath: /var/local/wasm
              name: wasm
          service:
            ports:
              - name: status-port
                nodePort: 30002
                port: 15021
                targetPort: 15021
              - name: http2
                nodePort: 30000
                port: 80
                targetPort: 8080
              - name: https
                nodePort: 30001
                port: 443
                targetPort: 8443
  profile: minimal
  tag: 1.13.2-distroless
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      defaultPodDisruptionBudget:
        enabled: false
      logging:
        level: default:debug
      proxy:
        componentLogLevel: misc:debug
        logLevel: debug
