name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.22.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Set up variables
        id: vars
        run: |
          echo "::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)"

      - name: Install Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '~1.17'

      - name: Install Make
        run: apt install make

      - name: Build
        run: make build

      - name: Upload built artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: charlescd.wasm-${{ steps.vars.outputs.COMMIT_HASH }}
          path: charlescd.wasm
          retention-days: 1

  test:
    strategy:
      matrix:
        image: [
          "istio/proxyv2:1.9.9",
          "istio/proxyv2:1.10.6",
          "istio/proxyv2:1.11.8",
          "istio/proxyv2:1.12.5",
          "istio/proxyv2:1.13.2",
        ]
    name: Test (${{ matrix.image }})
    needs: [ build ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: --privileged
    steps:
      - name: Install Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '~1.17'

      - name: Print Envoy version
        run: envoy --version

      - name: Install Make
        run: apt update && apt install make

      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Set up variables
        id: vars
        run: |
          echo "::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)"

      - name: Fetch built artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: charlescd.wasm-${{ steps.vars.outputs.COMMIT_HASH }}

      - name: Run e2e test
        run: make test
        env:
          CGO_ENABLED: "0"
